### ISSUE TITLE
Add support for pom.xml 

### ISSUE THREAD

**Issue by wesssup** [team172011/ta4jCharting#21]
Hi should be usefull to have a POM.xml option to download the lib inside java projects

**Comment by team172011** [comment]
Hi, what do you mean? This is a maven project with a pom.xml.

**Comment by wesssup** [comment]
https://gist.github.com/fernandezpablo85/03cf8b0cd2e7d8527063   ;-) 

So if you create your own JAVA project you can include yours like you also do with Spring for example ...

<servers>
    <server>
      <id>private-repo</id>
	   <configuration>
        <httpHeaders>
          <property>
            <name>Authorization</name>
            
            <value>Basic {Place the token here}</value>
          </property>
        </httpHeaders>
      </configuration>
    </server>
</server>

<repositories>
      <repository>
                    <id>private-repo</id>
                    `<name>Private` Repository</name>
                    <url>{Place the RAW github url here}</url>
                    <releases>
                        <enabled>true</enabled>
                        <updatePolicy>never</updatePolicy>
                    </releases>
                    <snapshots>
                        <enabled>false</enabled>
                    </snapshots>
       </repository>
</repositories>

**Comment by team172011** [comment]
Done with #23
