### ISSUE TITLE
Publish to maven central

### ISSUE THREAD

**Issue by kaen** [team172011/ta4jCharting#23]
I've found this library very helpful in working with ta4j, but setting up the dependency as a cloned git repo isn't very ergonomic. I know it's still versioned as a 0.x beta but I still think it would be helpful to publish it in its current state.

Thanks for the work you've all put in to this.

**Comment by team172011** [comment]
@kaen done! I configured github actions to automatically deploy snapshots when pushing to master and to automatically create a release when creating tags with name 'v*':

Current release:
```
<dependency>
  <groupId>de.sjwimmer.ta4j-charting</groupId>
  <artifactId>lib</artifactId>
  <version>0.1</version>
</dependency>
```
Current snapshot:
```
<dependency>
  <groupId>de.sjwimmer.ta4j-charting</groupId>
  <artifactId>lib</artifactId>
  <version>0.2-SNAPSHOT</version>
</dependency>
```
