### ISSUE TITLE
Change to Java 8

### ISSUE THREAD

**Issue by Cypher01** [team172011/ta4jCharting#24]
This is a great tool! I am creating an extension of ta4j-core, adding more indicators and rules. For compatibility reasons, I use the same Java version as ta4j-core, which is Java 8.

I'm using this library for testing, but it crashes, because it's built with Java 11.

The solution is simple. Change the Java version on pom.xml to 8. The required changes on the source code are very small, just type inference (`var` keyword) needs to be updated to use specific types instead.

If you want to, I can create a pull request.

**Comment by team172011** [comment]
@Cypher01 this is a good point! I implemented this tool to give others the possibility to test and work with Ta4j. Of course the language version should be the same. Feel free to make a PR 😉

**Comment by Cypher01** [comment]
The change was merged, so this issue can be closed.

**Comment by Cypher01** [comment]
The change was merged, so this issue can be closed.
